'use client';

import Link from 'next/link';
import { useState } from 'react';

export default function HomePage() {
  const [selectedLanguage, setSelectedLanguage] = useState('javascript');

  const languages = [
    { id: 'javascript', name: 'JavaScript', icon: '🟨', color: 'from-yellow-400 to-yellow-600' },
    { id: 'python', name: 'Python', icon: '🐍', color: 'from-blue-400 to-blue-600' },
    { id: 'typescript', name: 'TypeScript', icon: '🔷', color: 'from-blue-500 to-blue-700' },
    { id: 'java', name: 'Java', icon: '☕', color: 'from-red-400 to-orange-600' },
    { id: 'go', name: 'Go', icon: '🔵', color: 'from-cyan-400 to-cyan-600' },
    { id: 'rust', name: 'Rust', icon: '🦀', color: 'from-orange-400 to-orange-600' },
  ];

  const features = [
    {
      icon: '🎯',
      title: 'Adaptive Difficulty',
      description: 'Questions automatically adjust to your skill level. Get harder challenges as you improve.',
    },
    {
      icon: '🤖',
      title: 'AI-Powered',
      description: 'Unique questions generated by advanced AI. Never see the same question twice.',
    },
    {
      icon: '📊',
      title: 'Track Progress',
      description: 'Monitor your improvement with detailed analytics and performance metrics.',
    },
    {
      icon: '🔥',
      title: 'Build Streaks',
      description: 'Maintain daily learning streaks and earn bonuses for consistent practice.',
    },
    {
      icon: '💡',
      title: 'Smart Feedback',
      description: 'Get instant, helpful feedback on your answers with explanations.',
    },
    {
      icon: '🌍',
      title: '6 Languages',
      description: 'Master JavaScript, Python, TypeScript, Java, Go, and Rust.',
    },
  ];

  return (
    <div className="min-h-screen bg-white">
      {/* Navigation */}
      <nav className="fixed top-0 w-full bg-white/80 backdrop-blur-md border-b border-gray-200 z-50">
        <div className="max-w-7xl mx-auto px-6 py-4 flex items-center justify-between">
          <Link href="/" className="flex items-center gap-2">
            <span className="text-3xl">🧠</span>
            <span className="text-xl font-bold text-gray-900">Read The Code</span>
          </Link>
          <div className="flex items-center gap-6">
            <Link href="/about" className="text-gray-600 hover:text-gray-900 transition font-medium">
              About
            </Link>
            <Link href="/learn" className="px-6 py-2.5 bg-gray-900 text-white rounded-lg font-medium hover:bg-gray-800 transition shadow-sm">
              Start Learning
            </Link>
          </div>
        </div>
      </nav>

      {/* Hero Section */}
      <section className="pt-32 pb-20 px-6 bg-gradient-to-b from-gray-50 to-white">
        <div className="max-w-7xl mx-auto">
          <div className="text-center mb-16">
            <div className="inline-block mb-4 px-4 py-1.5 bg-blue-50 text-blue-700 rounded-full text-sm font-semibold">
              AI-Powered Learning Platform
            </div>
            <h1 className="text-6xl md:text-7xl font-bold text-gray-900 mb-6 leading-tight">
              Master Programming
              <br />
              <span className="text-blue-600">Through Adaptive Learning</span>
            </h1>
            <p className="text-xl text-gray-600 mb-8 max-w-2xl mx-auto leading-relaxed">
              AI-powered code comprehension questions that adapt to your skill level.
              Learn faster, retain more, and build real programming expertise.
            </p>
            <div className="flex gap-4 justify-center">
              <Link
                href="/learn"
                className="px-8 py-4 bg-gray-900 text-white rounded-lg text-lg font-semibold hover:bg-gray-800 transition shadow-lg shadow-gray-900/10"
              >
                Start Free Trial
              </Link>
              <a
                href="#features"
                className="px-8 py-4 bg-white text-gray-900 rounded-lg text-lg font-semibold border-2 border-gray-200 hover:border-gray-300 transition"
              >
                Learn More
              </a>
            </div>
          </div>

          {/* Language Selector Preview */}
          <div className="max-w-4xl mx-auto">
            <div className="bg-white rounded-2xl border border-gray-200 p-8 shadow-xl">
              <h3 className="text-gray-900 text-lg font-semibold mb-6 text-center">
                Choose Your Language
              </h3>
              <div className="grid grid-cols-2 md:grid-cols-3 gap-4">
                {languages.map((lang) => (
                  <button
                    key={lang.id}
                    onClick={() => setSelectedLanguage(lang.id)}
                    className={`p-6 rounded-xl border-2 transition ${selectedLanguage === lang.id
                        ? 'border-blue-600 bg-blue-50 shadow-md'
                        : 'border-gray-200 bg-white hover:border-gray-300 hover:shadow-sm'
                      }`}
                  >
                    <div className="text-4xl mb-2">{lang.icon}</div>
                    <div className="text-gray-900 font-semibold">{lang.name}</div>
                  </button>
                ))}
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* Features Section */}
      <section id="features" className="py-24 px-6 bg-gray-50">
        <div className="max-w-7xl mx-auto">
          <div className="text-center mb-16">
            <h2 className="text-4xl md:text-5xl font-bold text-gray-900 mb-4">
              Why Choose Read The Code?
            </h2>
            <p className="text-xl text-gray-600">
              The smartest way to improve your coding skills
            </p>
          </div>

          <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-8">
            {features.map((feature, index) => (
              <div
                key={index}
                className="bg-white rounded-xl border border-gray-200 p-8 hover:shadow-lg hover:border-gray-300 transition group"
              >
                <div className="text-5xl mb-4 group-hover:scale-110 transition">
                  {feature.icon}
                </div>
                <h3 className="text-xl font-bold text-gray-900 mb-3">
                  {feature.title}
                </h3>
                <p className="text-gray-600 leading-relaxed">{feature.description}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* How It Works */}
      <section className="py-24 px-6 bg-white">
        <div className="max-w-7xl mx-auto">
          <div className="text-center mb-16">
            <h2 className="text-4xl md:text-5xl font-bold text-gray-900 mb-4">
              How It Works
            </h2>
            <p className="text-xl text-gray-600">
              Start learning in 3 simple steps
            </p>
          </div>

          <div className="grid md:grid-cols-3 gap-12">
            <div className="text-center">
              <div className="w-16 h-16 bg-blue-600 rounded-2xl flex items-center justify-center text-2xl font-bold text-white mx-auto mb-6 shadow-lg shadow-blue-600/20">
                1
              </div>
              <h3 className="text-2xl font-bold text-gray-900 mb-4">
                Choose a Language
              </h3>
              <p className="text-gray-600 leading-relaxed">
                Select from 6 popular programming languages to start your journey
              </p>
            </div>

            <div className="text-center">
              <div className="w-16 h-16 bg-blue-600 rounded-2xl flex items-center justify-center text-2xl font-bold text-white mx-auto mb-6 shadow-lg shadow-blue-600/20">
                2
              </div>
              <h3 className="text-2xl font-bold text-gray-900 mb-4">
                Answer Questions
              </h3>
              <p className="text-gray-600 leading-relaxed">
                Read code snippets and answer comprehension questions
              </p>
            </div>

            <div className="text-center">
              <div className="w-16 h-16 bg-blue-600 rounded-2xl flex items-center justify-center text-2xl font-bold text-white mx-auto mb-6 shadow-lg shadow-blue-600/20">
                3
              </div>
              <h3 className="text-2xl font-bold text-gray-900 mb-4">
                Level Up
              </h3>
              <p className="text-gray-600 leading-relaxed">
                Watch your difficulty increase as you master each concept
              </p>
            </div>
          </div>
        </div>
      </section>

      {/* CTA Section */}
      <section className="py-24 px-6 bg-gray-900">
        <div className="max-w-4xl mx-auto text-center">
          <h2 className="text-4xl md:text-5xl font-bold text-white mb-6">
            Ready to Level Up Your Skills?
          </h2>
          <p className="text-xl text-gray-300 mb-8">
            Join thousands of developers improving their coding abilities every day
          </p>
          <Link
            href="/learn"
            className="inline-block px-12 py-5 bg-blue-600 text-white rounded-lg text-xl font-semibold hover:bg-blue-700 transition shadow-xl shadow-blue-600/20"
          >
            Start Learning Now →
          </Link>
        </div>
      </section>

      {/* Footer */}
      <footer className="bg-gray-50 border-t border-gray-200 py-12 px-6">
        <div className="max-w-7xl mx-auto">
          <div className="grid md:grid-cols-4 gap-8 mb-8">
            <div>
              <div className="flex items-center gap-2 mb-4">
                <span className="text-3xl">🧠</span>
                <span className="text-xl font-bold text-gray-900">Read The Code</span>
              </div>
              <p className="text-gray-600">
                Adaptive code learning powered by AI
              </p>
            </div>

            <div>
              <h4 className="text-gray-900 font-semibold mb-4">Product</h4>
              <ul className="space-y-2">
                <li>
                  <Link href="/learn" className="text-gray-600 hover:text-gray-900 transition">
                    Start Learning
                  </Link>
                </li>
                <li>
                  <Link href="/about" className="text-gray-600 hover:text-gray-900 transition">
                    About
                  </Link>
                </li>
              </ul>
            </div>

            <div>
              <h4 className="text-gray-900 font-semibold mb-4">Legal</h4>
              <ul className="space-y-2">
                <li>
                  <Link href="/terms" className="text-gray-600 hover:text-gray-900 transition">
                    Terms of Service
                  </Link>
                </li>
                <li>
                  <Link href="/privacy" className="text-gray-600 hover:text-gray-900 transition">
                    Privacy Policy
                  </Link>
                </li>
              </ul>
            </div>

            <div>
              <h4 className="text-gray-900 font-semibold mb-4">Connect</h4>
              <ul className="space-y-2">
                <li>
                  <a href="https://github.com/isuru0x01" className="text-gray-600 hover:text-gray-900 transition">
                    GitHub
                  </a>
                </li>
              </ul>
            </div>
          </div>

          <div className="border-t border-gray-200 pt-8 text-center text-gray-600">
            <p>© 2025 Read The Code. All rights reserved.</p>
          </div>
        </div>
      </footer>
    </div>
  );
}
