'use client';

import Link from 'next/link';
import { SiteHeader } from '@/components/site-header';

export default function TermsPage() {
    return (
        <div className="min-h-screen bg-white">
            {/* Navigation */}
            {/* Navigation */}
            <SiteHeader />

            {/* Content */}
            <div className="pt-32 pb-20 px-6">
                <div className="max-w-4xl mx-auto">
                    <div className="bg-white rounded-2xl border border-gray-200 p-12 shadow-xl">
                        <h1 className="text-5xl font-bold text-gray-900 mb-4">Terms of Service</h1>
                        <p className="text-gray-500 mb-8">Last updated: December 12, 2024</p>

                        <div className="space-y-8 text-gray-600 leading-relaxed">
                            <section>
                                <h2 className="text-2xl font-bold text-gray-900 mb-4">1. Acceptance of Terms</h2>
                                <p>
                                    By accessing and using Read The Code, you accept and agree to be bound by the terms and provision of this agreement. If you do not agree to these terms, please do not use our service.
                                </p>
                            </section>

                            <section>
                                <h2 className="text-2xl font-bold text-gray-900 mb-4">2. Use License</h2>
                                <p>
                                    Permission is granted to temporarily use Read The Code for personal, non-commercial learning purposes. This is the grant of a license, not a transfer of title, and under this license you may not:
                                </p>
                                <ul className="list-disc list-inside mt-3 space-y-2 ml-4">
                                    <li>Modify or copy the materials</li>
                                    <li>Use the materials for any commercial purpose</li>
                                    <li>Attempt to decompile or reverse engineer any software</li>
                                    <li>Remove any copyright or other proprietary notations</li>
                                </ul>
                            </section>

                            <section>
                                <h2 className="text-2xl font-bold text-gray-900 mb-4">3. User Accounts</h2>
                                <p>
                                    When you create an account with us, you must provide accurate, complete, and current information. Failure to do so constitutes a breach of the Terms, which may result in immediate termination of your account.
                                </p>
                            </section>

                            <section>
                                <h2 className="text-2xl font-bold text-gray-900 mb-4">4. Content</h2>
                                <p>
                                    All content generated by our AI system, including code snippets and questions, is provided for educational purposes only. While we strive for accuracy, we make no warranties about the completeness, reliability, or accuracy of this information.
                                </p>
                            </section>

                            <section>
                                <h2 className="text-2xl font-bold text-gray-900 mb-4">5. Privacy</h2>
                                <p>
                                    Your use of Read The Code is also governed by our Privacy Policy. Please review our Privacy Policy, which also governs the site and informs users of our data collection practices.
                                </p>
                            </section>

                            <section>
                                <h2 className="text-2xl font-bold text-gray-900 mb-4">6. Limitation of Liability</h2>
                                <p>
                                    In no event shall Read The Code or its suppliers be liable for any damages (including, without limitation, damages for loss of data or profit, or due to business interruption) arising out of the use or inability to use the materials on Read The Code.
                                </p>
                            </section>

                            <section>
                                <h2 className="text-2xl font-bold text-gray-900 mb-4">7. Modifications</h2>
                                <p>
                                    Read The Code may revise these terms of service at any time without notice. By using this platform, you are agreeing to be bound by the then current version of these terms of service.
                                </p>
                            </section>

                            <section>
                                <h2 className="text-2xl font-bold text-gray-900 mb-4">8. Contact Information</h2>
                                <p>
                                    If you have any questions about these Terms, please contact us through our GitHub repository or support channels.
                                </p>
                            </section>
                        </div>

                        <div className="mt-12 pt-8 border-t border-gray-200">
                            <Link href="/" className="text-blue-600 hover:text-blue-700 transition font-medium">
                                ← Back to Home
                            </Link>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    );
}
